"""Added description and category to Menu

Revision ID: 8135c4e55e8a
Revises: 
Create Date: 2024-08-21 10:39:36.013344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8135c4e55e8a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=False))
        batch_op.alter_column('price',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
        batch_op.drop_column('category')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
